export default function Head(){
  return(
    <>
      <title>About</title>
      <meta content = "width = device-width, initial-scale = 1" name="view" />
      <meta name="description" content="Generated by"/>
      <link rel="icon" href="/favicon.ico"/>
    </>
  )
}
